# Generated by Django 5.1.2 on 2024-10-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_description_produto_nome_remove_produto_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
