# Generated by Django 5.1.2 on 2024-10-15 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_produto_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='description',
            new_name='descricao',
        ),
    ]
